### ISSUE TITLE
WIFI: Fails with this error: sdio write failed (-110) 

### ISSUE THREAD

**Issue by docularxu** [96boards/bugs#17] opened 2015-03-11 01:07 UTC
In debian, when wlan0 is configured in interface.d, during debian booting, wpa_supplicant can easily trigger an sdio error. This is fatal to WiFi, as it can never recover.

See logs and analysis:

[  OK  ] Started LSB: Set console font and keymap.
[   40.703181] Call trace:
[   40.706632] wl1271_sdio mmc2:0001:2: sdio write failed (-110)
[   40.712964] Call trace:
[   40.716711] Call trace:
[   40.719692] wlcore: ERROR failed to send stop firmware logger command
[   40.952689] wlcore: ERROR firmware boot failed despite 3 retries
[  *** ] A start job is running for LSB: Raise network interf...51s / no limit)

1. the first error is: "sdio write failed"
 wpa_supplicant --> nl80211_trigger_scan --> wl12xx_sdio_raw_write --> wl1271_sdio mmc2:0001:2: sdio write failed (-110)

2. after this, wlcore tries to recover, but still fails. There are two call traces:
 1) wpa_supplicant --> wl12xx_queue_recovery_work
 2) kworker workqueue: wl1271_recovery_work -> wlcore_cmd_send_failsafe
Finally, wlcore prints:
[   38.886826] wlcore: ERROR failed to send stop firmware logger command
[   38.893527] wlcore: Hardware recovery in progress. FW ver: Rev 8.8.0.0.13
[   38.893550] wlcore: down
[   39.113190] wlcore: ERROR firmware boot failed despite 3 retries

==

**Comment by ldts** [comment] 2015-03-12 17:54
transferred to 96boards/linux#16

**Comment by ldts** [comment] 2015-03-16 15:42
The failure always comes after a SDIO CMD 52. And so far in my tests it is triggered by either 
a) a wifi scan or 
b) by a wifi wpa re-association (when connection is lost).

[ 97.370478] Enter mmc_io_rw_direct_host()
[ 97.370658] dwmmc_k3 f723f000.dwmmc2: CMD 52(arg=0x83fff801) REP time out
[ 97.385843] dw_mci_command_complete(): dw_mci host->cmd_status error: SDMMC_INT_RTO
[ 97.385873] dw_mci_command_complete(): set cmd->error to -110, -110
[ 97.385987] mmc2: req failed (CMD52): -110, retrying...

Now checking sdio first.
However, WiFi should also be checked, what's the special thing when doing a scan/association? a power failure or what?

**Comment by ldts** [comment] 2015-03-16 15:43
more tests show that this failure is closely related to TI WIFI ELP (extreme low power mode). Error happens when trying to wake up from ELP mode.

[ 93.089736] wl1271_sdio mmc2:0001:2: sdio write 53 addr 0x50f0, 4 bytes
[ 93.097728] s3.2
[ 93.122434] wlcore: elp work
[ 93.122443] wlcore: chip to elp
[ 93.122450] s1
[ 93.122455] Enter mmc_io_rw_direct_host()
[ 93.122503] wl1271_sdio mmc2:0001:2: sdio write 52 addr 0x1fffc, byte 0x00
[ 109.509992] wlcore: waking up chip from elp
[ 109.510055] s1
[ 109.510086] Enter mmc_io_rw_direct_host()
[ 109.510263] dwmmc_k3 f723f000.dwmmc2: CMD 52(arg=0x83fff801) REP time out
[ 109.525572] dw_mci_command_complete(): dw_mci host->cmd_status error: SDMMC_INT_RTO

**Comment by ldts** [comment] 2015-03-16 15:43
@sbambrough 

About issue: wl1271_sdio mmc2:0001:2: sdio write failed (-110)

in Debian when configured in /etc/network/interfaces.d/wlan0 and WiFi is up and connected when system booting, it is very easy to observe a WiFi hang. The reason of this lies in firmware cannot be waken up from ELP (Extreme Low Power) mode. Note: not every wakeup from ELP mode will fail, there are still unknown 'random' factors. So right, the issue is not rootcaused. But,

Workaround exists: disable ELP mode. We will update the config to do this automatically in the builds

In the meantime: 
Do this before wlan0 up:
iw wlan0 set power_save off
echo 0> /sys/kernel/debug/ieee80211/phy0/wlcore/sleep_auth
ifconfig wlan0 up

**Comment by docularxu** [comment] 2015-03-26 09:34
Now I'm in touch with TI FAE: Eyal. He suggested me not to use the in mainline wl18 driver, instead to use their R8.5 release. I am building that now. However, due to different arch (arm64) and toolchain, TI's build script when used directly will cause errors. I am working with Eyal to solve that.

**Comment by sbambrough** [comment] 2015-05-04 18:24
WIFI works for me first time ever.  This error no longer occurs.

**Closed by sbambrough** 2015-05-04 18:24 UTC
Labels: Android Image, Debian Image, kernel
