### ISSUE TITLE
USB speed change requires hardware intervention

### ISSUE THREAD

**Issue by gcgrey** [96boards/bugs#85] opened 2015-05-07 17:34 UTC
To change the USB speed (low/full vs high) you must do the following:
1. Execute usb_speed --high or --full
2. Remove one of the following from the microUSB OTG port on HiKey (which means insert it first if it is not already in):
a. A microUSB cable configured for host devices - i.e. with a host Type A port that you could plug a USB stick into on the other end (can be just the cable), or
b. A microUSB cable configured for target devices - i.e with a normal Type A connector on the other end plugged into a host computer (will not work if it is not connected to a powered device on the other end)

This will then change the mode. This is not an acceptable user experience. 
We need to understand what software changes are needed to make this a software only switch.

**Comment by gaozhangfei** [comment] 2015-05-08 02:51
Just want to make sure: 
The speed change only takes effect after remove the micro usb, which will change to host mode and only in this very moment, the new config will be checked.

case 1: in host mode -> change speed -> speed is not changed -> plug micro usb cable -> unplug usb cable -> speed changed
case 2: device mode -> change speed -> unplug usb cable -> speed changed.

So the operation unplug micro usb is required, which make device mode -> host mode (only check speed at this moment)

In git log and doc as well
    2. If user want to switch speed.
    mount -t debugfs none /mnt
    cd /mnt/f72c0000.usb/
    cat config
    echo 1 > config /* switch to full speed */
    echo 0 > config /* switch to high speed */
    
    Then unplug usb, host mode will switch to full speed, all ports don't support high speed in host mode.
    Every time switch speed, just need plug usb -> unplug usb from OTG.

**Comment by sbambrough** [comment] 2015-05-08 02:59
There is a script on the image /home/linaro/bin/usb_speed_switch that will
do all of the things in 2.  Needs to be run as root.
Is there a way to fake the usb unplug, so it becomes unnecessary to do it?
This would be much preferable.  Please investigate.
Question: Hispeed only works on the OTG port?
Question: The A ports only work at full speed?
Question: If you plug a hispeed device into the OTG port, will it switch
automatically to high speed?





On Thu, May 7, 2015 at 10:51 PM, Zhangfei Gao <notifications@github.com>
wrote:

> Just want to make sure:
> The speed change only takes effect after remove the micro usb, which will
> change to host mode and only in this very moment, the new config will be
> checked.
>
> case 1: in host mode -> change speed -> speed is not changed -> plug micro
> usb cable -> unplug usb cable -> speed changed
> case 2: device mode -> change speed -> unplug usb cable -> speed changed.
>
> So the operation unplug micro usb is required, which make device mode ->
> host mode (only check speed at this moment)
>
> In git log and doc as well
> 2. If user want to switch speed.
> mount -t debugfs none /mnt
> cd /mnt/f72c0000.usb/
> cat config
> echo 1 > config /* switch to full speed
> */ echo 0 > config /* switch to high speed */
>
> Then unplug usb, host mode will switch to full speed, all ports don't support high speed in host mode.
> Every time switch speed, just need plug usb -> unplug usb from OTG.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/96boards/bugs/issues/85#issuecomment-100080873>.
>



-- 
Scott Bambrough
Technical Director, Member Services
Linaro <http://www.linaro.org>

**Comment by gaozhangfei** [comment] 2015-05-08 03:14
There is a script on the image /home/linaro/bin/usb_speed_switch that will
do all of the things in 2.  Needs to be run as root.
Is there a way to fake the usb unplug, so it becomes unnecessary to do it?
This would be much preferable.  Please investigate.

[zf] When unplug micro USB, interrupt will happen and switch to host mode, when config is checked.
So all we do just need change the config and wait the interrupt to check, this workaround is very small.
But if we generate a false interrupt, the effort is too big, which may break the state machine.

By the way, the speed change is specifically for A ports. which has silicon issue and need such workaround.

Question: Hispeed only works on the OTG port?
[zf] OTG can work at high/ full /low speed

Question: The A ports only work at full speed?
[zf] 
When set speed to full, A port only work at full speed.
When set speed to high, A port only work at high speed, does not support full speed.


Question: If you plug a hispeed device into the OTG port, will it switch
automatically to high speed?
[zf] No, 
Since the silicon cut the split function for simple, it can not switch automatically.

**Comment by sbambrough** [comment] 2015-05-08 03:22
You tell me the OTG port supports operation at low/full/high speeds.  You
say it will not switch automatically to high speed in the last question.
But you say earlier speed change is specifically for A ports.  So how to
get high speed on OTG port?

Question: All devices on the port must operate at the same speed?
Question: Only one of OTG or A ports can be operated at a time.  If using
OTG, A ports will not work, and vice versa?


On Thu, May 7, 2015 at 11:14 PM, Zhangfei Gao <notifications@github.com>
wrote:

> There is a script on the image /home/linaro/bin/usb_speed_switch that will
> do all of the things in 2. Needs to be run as root.
> Is there a way to fake the usb unplug, so it becomes unnecessary to do it?
> This would be much preferable. Please investigate.
>
> [zf] When unplug micro USB, interrupt will happen and switch to host mode,
> when config is checked.
> So all we do just need change the config and wait the interrupt to check,
> this workaround is very small.
> But if we generate a false interrupt, the effort is too big, which may
> break the state machine.
>
> By the way, the speed change is specifically for A ports. which has
> silicon issue and need such workaround.
>
> Question: Hispeed only works on the OTG port?
> [zf] OTG can work at high/ full /low speed
>
> Question: The A ports only work at full speed?
> [zf]
> When set speed to full, A port only work at full speed.
> When set speed to high, A port only work at high speed, does not support
> full speed.
>
> Question: If you plug a hispeed device into the OTG port, will it switch
> automatically to high speed?
> [zf] No,
> Since the silicon cut the split function for simple, it can not switch
> automatically.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/96boards/bugs/issues/85#issuecomment-100085345>.
>



-- 
Scott Bambrough
Technical Director, Member Services
Linaro <http://www.linaro.org>

**Comment by gaozhangfei** [comment] 2015-05-08 03:31
OTG port has no hub, no need of split funciton, so it can support low/full/high speeds.

A ports: there is hub attached, but no split function, so it can not switch, only works at either high or full/low speed.

There is only one controller in the chip, so OTG and A ports can work not work at the same time, while OTG takes high priority per board design.
All devices in A ports should be same speed, since no split.

**Comment by gcgrey** [comment] 2015-05-08 12:02
Please explain how to put A ports into high speed mode. 
(1) What I expected:
Execute bin/usb_speed --high
Result: no change - ports stay in low/full speed mode
(2) What I tried
Execute bin/usb_speed --high
Plug in and then unplug USB microUSB-USB A cable to microUSB port
Result: still no change - ports stay in low/full speed mode
(3)
Plug in microUSB cable to microUSB port
Execute bin/usb_speed --high
Unplug microUSB cable
Result: same as (2)

**Comment by gcgrey** [comment] 2015-05-08 12:17
OK - here is what you have to do:
1. Execute bin/usb_speed --high
2. Plug in and unplug an actual device to the microUSB port (a microUSB to USB cable or OTG cable alone is not enough)
3. Then the ports are in high speed mode. 
4. The same applies when you want to revert to full/low speed - i.e. you have to Plug in and unplug a device from the microUSB port for the A ports to revert. 
This is not a good user experience. Why can we not make the execution of the usb_speed utility be sufficient?

**Comment by gaozhangfei** [comment] 2015-05-08 14:00
1, when micro usb cable is unpluged from otg port, it will switch from device mode to host mode.
2. switching to host mode -> check the config -> host_init.
Only at this moment, the config will be checked and set.

1. usb_speed  is just change the config, not takes effect.
2. unplug micro usb -> device mode to host mode -> host_init -> check new flag.

This workaround is very simple, no need to touch state machine and break the common usb code.
Only need change config, make switch device->host (host_init)

**Comment by sbambrough** [comment] 2015-05-08 14:49
We need to find another way to do this, unplugging and plugging in a USB device is not acceptable.

**Comment by gcgrey** [comment] 2015-05-08 17:32
The current status is as follows after further testing:
To change the mode (low/full vs high) you must do the following:
1. Execute usb_speed --high or --full
2. Remove one of the following from the microUSB OTG port on HiKey (which means insert it first if it is not already in):
a. A microUSB cable configured for host devices - i.e. with a host Type A port that you could plug a USB stick into on the other end (can be just the cable), or
b. A microUSB cable configured for target devices - i.e with a normal Type A connector on the other end plugged into a host computer (will not work if it is not connected to a powered device on the other end)

This will then change the mode.
This is not an acceptable user experience. 
We need to understand what software changes are needed to make this a software only switch.

**Comment by gaozhangfei** [comment] 2015-05-11 10:17
https://github.com/96boards/linux/pull/70

Simulate interrupt in host mode, though I think it is risky, since current operation is stopped and switch to other speed.
If in device mode, ignore, waiting for device->host.

**Comment by gcgrey** [comment] 2015-05-11 11:36
Yes - this is tricky. 
If in device mode (OTG connected to PC) print message:
"Mode switch can only be carried out when microUSB is disconnected or in host mode" and exit
If in host mode I think what you need to do is like an SD eject operation:
1. In the utility ask the user to confirm that the USB ports are not in use. 
Please confirm that any attached USB devices are not in current use before mode change ...
[y/n]
If y proceed, if n print message:
Please try again later when USB ports are not in use. 
2. Then proceed with the interrupt simulation.

**Comment by sbambrough** [comment] 2015-05-11 11:46
Is there a way for userland to determine what mode (device/host) a port is
in?

How does userland do the interrupt simulation?

Scott

Scott Bambrough
Technical Director, Member Services
Linaro

**Comment by gaozhangfei** [comment] 2015-05-11 12:00
User land can not determine what mode it is.
The mode relies on the hardware status.

If the board is connected with micro usb, it is in device mode.
If micro usb is empty, it switch to host mode by default.

Here is calling the interrupt function from micro usb unplug.

Personally, I think it is just a workaround, the simpler the better.

**Comment by gcgrey** [comment] 2015-05-11 12:35
if a microUSB is inserted then we know (GPIO2_6) which is used to then switch to the microUSB port rather than the host ports. 
USB_ID_DET is also available on GPIO2_5 to determine whether host or device mode

**Comment by gaozhangfei** [comment] 2015-05-11 13:53
Maybe I am not make it clear

Background: speed is only for host, A ports (OTG can support all speed)
1. If OTG is conencted, device mode
Just set speed vector, when micro usb is unpluged, switch to host mode with the new speed.

2. If OTG is not connected, host mode (no matter A port is connect or not)
Directly set speed and calling interrupt function:
queue_work(hsotg->wq_otg, &hsotg->wf_otg) -> dwc2_conn_id_status_change -> host reinit
So the risk is the on-going operation will be stopped, which I think is OK for workaround.

After all it is just a workaround.
In fact, I still think the original method is safer, counting on micro usb unplug and checking the new speed.

**Comment by gcgrey** [comment] 2015-05-11 21:26
The system is by default in Full/Low speed host mode to enable keyboard/mouse. 
This also affects the microUSB port when used in host mode. 
To use the microUSB port in high speed host mode you have to plug in the device, execute utility to swap to high speed, unplug the device, plug it back in and then use it.  This is not a good user experience.
To use the A ports in high speed you have to execute the utility to swap to high speed, then either unplug a device cable from microUSB or a cable connected to a powered PC from the microUSB. This is not a good user experience. 

This is still my recommendation:

If in device mode (OTG connected to PC - detect via GPIO2_5 and 2_6) print message:
"Mode switch can only be carried out when microUSB is disconnected or in host mode" and exit.
(This may not actually be true but it simplifies the user experience as you cannot tell whether the PC is about to do something) 

If in host mode (also detect via GPIO2_5 and 2_6) then
1. In the utility 
a. if possible wait for no activity and then block all new activity until after the interrupt simulation, or if that's too hard then
b. ask the user to confirm that the USB ports are not in use. 
"Please confirm that any attached USB devices are not in current use before mode change ..."
[y/n]
If y proceed with the interrupt simulation
If n print message:
"Please make mode switch later when USB ports are not in use." and exit

If you have better ideas I'd like to hear them, but asking a user to plug and unplug a microUSB cable in order to switch speeds on a Type A port is not acceptable.

**Comment by gaozhangfei** [comment] 2015-05-12 01:12
The board is in full/low speed only for A port.
For micro USB port, it is always support high/full/low speed.

usb_speed only changes A port speed, modifying host register only.
Even attach usb to micro usb port, it is still in device mode.

So what we do here is only related with A port.
And the only risk is usb_speed during A port transaction, like U disk copying.
We can add it in readme or document, since usb_speed is not frequently been used.

**Comment by gcgrey** [comment] 2015-05-12 01:16
Attach a USB stick to microUSB and device is limited to full speed unless you do the usb-speed switch.
George

**Comment by gaozhangfei** [comment] 2015-05-12 07:34
Yes, you are right, 
After double checked, 
If OTG works in HOST mode (attaching u-disk or ethernet coverter), it also impacted usb-speed switch.
If OTG works in device mode, it has nothing to do with usb-speed switch.

And current workaround also works for OTG in host mode, since it will check the current working mode.

1, If in device mode, OTG works as gadget, just save the new speed.
When micro usb line is unpluged, switch to host mode with new speed.

2. If in host mode, including A ports and OTG attaching with a device, stop current transaction and host restart with new speed.

**Comment by gaozhangfei** [comment] 2015-05-20 00:10
Current code has already merged this patch:

commit fb5b8313abc7f83c732587fde5fd822ec0ffacd7
| | Author: Zhangfei Gao <zhangfei.gao@linaro.org>
| | Date:   Mon May 11 17:57:18 2015 +0800
| | 
| |     usb: dwc2: workaround of host usb_speed
| |     
| |     usb_speed takes effect immediately if in host mode.

Expected behavior:
OTG device mode: support all speed, no impact.

host mode (OTG & A port)： when running usb-speed switch, current transaction will be stopped, and re-start with the new speed.

**Comment by docularxu** [comment] 2015-05-20 08:36
Verified on http://builds.96boards.org/snapshots/hikey/debian/303. Hardware intervention is not required any more. It means on both Port A's and OTG host:
To change usb from full to high: you only need to run the command './usb_speed -s high'.
To change usb from high to full: you only need to run the command './usb_speed -s full'.

You don't need to plug on/off any cables, upon executing of the above command, USB devices get re-enumerated for the new speed.

**Closed by docularxu** 2015-05-20 08:36 UTC
Labels: Debian Image, kernel

**Comment by docularxu** [comment] 2015-05-21 06:03
Checked on Android (#110) and Debian (#303):

usb_speed -s high:
	Type A: 
		accepts high-speed USB device, and it works at high-speed.
		low- and full-speed USB device cannot be enumerated.
	OTG + otg adapter cable: 
		accepts low-, full- and high-speed USB device, and works at their respective speed mode.

usb_speed -s full:
	Type A: 
		accepts high-speed USB device, but it works at (topped by) full-speed.
		accepts low- and full-speed USB device.
	OTG + otg adapter cable: 
		accepts high-speed USB device, but it works at (topped by) full-speed.
		accepts low- and full-speed USB device.

-Guodong Xu
