### ISSUE TITLE
HiKey - Kernel -  Blank screen (no X) upon boot up on recent ALIP builds.

### ISSUE THREAD

**Issue by usmanahmad-linaro** [96boards/bugs#34] opened 2015-03-26 07:01 UTC
On recent ALIP builds at http://builds.96boards.org/snapshots/hikey/debian, after the board boots, we get a blank screen and no desktop comes up.

**Comment by docularxu** [comment] 2015-03-26 09:06
scott checked this issue and have the following findings. I am asking Xinliang to check.

>> from Scott:
I had a look at this failure, debugged this a bit...

Started with latest snapshot (135), X fails to load.

Rebuild kernel with the latest git, hikey-mali branch
Rebuild boot and system images using latest kernel, setup networking
via eth0 by default so I can ssh in.
Flash boot and system partitions using rebuilt images.

Findings:
1. # apt-get install libgl1-mesa-dri
2. missing set_busid in struct drm_driver hisi_drm_driver
3. Why do these errors occur?
[    2.412661] [drm:hisi_dsi_probe] *ERROR* failed to find slave
encoder i2c client
[    3.602363] hisi-drm smb:display-subsystem: DSI-1: EDID block 0 invalid.

**Comment by docularxu** [comment] 2015-03-27 04:37
Flash this debian rootfs image: https://builds.96boards.org/snapshots/hikey/debian/133/hikey-jessie_alip_20150320-133.emmc.img.gz
onto a Hikey board. ($ fastboot flash system xxx).

Then, 
if using kernel from debian build 124 ($ fastboot flash boot xxx), (https://builds.96boards.org/snapshots/hikey/debian/124/boot-fat.emmc.img.gz), X can show up on HDMI monitor successfully;
if using kernel from debian build 125 ($ fastboot flash boot xxx), (https://builds.96boards.org/snapshots/hikey/debian/125/boot-fat.emmc.img.gz), X can NOT show up on HDMI monitor.

Need to check changes between kernel 125 and 124. 

Note that DRM patches are integrated on Mar/6 into kernel 125:

Commit: 7bfade6d37fc2eb28b9c9f26219b84fd1e2c8f28
 Merge pull request #8 from ldts/hikey
 gpu/drm: hisilicon patchset addressing display issues

**Comment by docularxu** [comment] 2015-04-08 01:31
Fixed with this commit: c87bedf
I verified with my monitor.

Build 253 should have included this commit.
https://builds.96boards.org/snapshots/hikey/debian/253

**Comment by docularxu** [comment] 2015-04-08 01:36
Note:
On my Dell U2412M monitor + HDMI to Disport port cable, it happened twice yesterday that the X window blinks (into black screen then back to normal desktop) at a frequency about 4 seconds. However, since later last night, till this morning, I have tried another about 5 times, this cannot be reproduced any more.

I leave this note here, and expect others with HDMI monitors can test and report back. If no other failure reports, I suggest to close this issue.

**Comment by docularxu** [comment] 2015-04-14 00:32
Verified on build 254 (https://builds.96boards.org/snapshots/hikey/debian/254), pass. So I will close this issue. 

Known issue: 
There is one regression, tracked by https://github.com/96boards/bugs/issues/41

**Closed by docularxu** 2015-04-14 00:32 UTC
