### ISSUE TITLE
No display on HDMI monitor using Debian image and ARM TF/UEFI.

### ISSUE THREAD

**Issue by Leo-Yan** [96boards/bugs#68] opened 2015-04-29 01:36 UTC
If boot w/t ATF/UEFI, hdmi cannot work well and cannot display on monitor. Reproduced w/t below images:

Boot images:
https://builds.96boards.org/snapshots/hikey/uefi/16

Kernel:
https://builds.96boards.org/snapshots/hikey/debian/272/boot-fat.uefi.img.gz

Rootfs:
https://builds.96boards.org/snapshots/hikey/debian/272/hikey-jessie_alip_20150423-272.emmc.img.gz

**Comment by sbambrough** [comment] 2015-05-05 21:42
Not sure exactly what the problem is here.   Are you looking for ATF/UEFI output on the HDMI monitor as the system boots?

**Comment by Leo-Yan** [comment] 2015-05-06 01:20
On Tue, May 05, 2015 at 02:42:52PM -0700, Scott Bambrough wrote:
> Not sure exactly what the problem is here.   Are you looking for ATF/UEFI output on the HDMI monitor as the system boots?

If we boot Debian w/t ATF/UEFI as boot loaders, then x window cannot
be displayed on HDMI monitor. So that means if we use ATF/UEFI, then
hdmi or display related modules in kernel cannot work properly.

**Comment by xin3liang** [comment] 2015-06-02 01:38
It's fixed now.  HDMI's power supply initialize within the bootloader.
Haojian will update the l-loader.bin which including HDMI's power supply initialization and fix this problem. 
Please check it after the l-loader.bin is updated.

**Comment by hzhuang1** [comment] 2015-06-02 01:47
https://github.com/96boards/arm-trusted-firmware/pull/39

Fixed in this pull request.

**Closed by hzhuang1** 2015-06-02 01:47 UTC
Labels: Board - HiKey, Bootloader - ARM TF, Bootloader - UEFI, Image - Debian
