### ISSUE TITLE
USB mode switch fails in Android with attached USB keyboard/mouse

### ISSUE THREAD

**Issue by gcgrey** [96boards/bugs#113] opened 2015-05-21 12:48 UTC
I have a Gear Head Window mini-smart touch USB keyboard (KB3700TP) - keyboard/trackpad combo device
On Debian the USB mode switch works as expected. If you switch using the keyboard the mode switches and the keyboard is no longer available on an A port. 

If I do the switch on Android (Snapshot 110) with the keyboard/mouse attached the switch does not "stick" - the UI switches to High speed mode for a second and then reverts to Full Speed mode. The mouse/keyboard also stops working and then restarts a couple of seconds later. 

If I disconnect the Gear Head USB keyboard and use a Bluetooth keyboard/mouse device to make the switch then it works as expected. The board goes into High Speed mode and stays there.

**Comment by sbambrough** [comment] 2015-05-21 12:57
I see the same behaviour with a Logitech K400r keyboard/mouse combo.

**Comment by vishalbhoj** [comment] 2015-05-21 13:55
I am able to reproduce the issue. Will investigate it. Looks like an app bug.

**Comment by vishalbhoj** [comment] 2015-05-22 04:02
fixed in http://builds.96boards.org/snapshots/hikey/aosp/117

**Closed by vishalbhoj** 2015-05-22 04:02 UTC
Labels: AOSP Image, kernel
