### ISSUE TITLE
Powering on bluetooth takes too long....

### ISSUE THREAD

**Issue by sbambrough** [96boards/bugs#78] opened 2015-05-04 22:33 UTC
```
root@linaro-alip:~# time /bin/hciconfig hci0 up

real	1m10.805s
user	0m0.000s
sys	0m0.420s
root@linaro-alip:~# ^C
root@linaro-alip:~# 
```
It takes almost 71s to bring the BT adapter up.

**Comment by docularxu** [comment] 2015-05-05 11:30
That is caused by downloading firmware. It is in this routine: download_firmware(), of drivers/misc/ti-st/st_kim.c where 70 seconds are consumed.
 [   27.911476] (stk) :ti-connectivity/TIInit_11.8.32.bts
In this 71seconds, on average, 0.142 second per command/response pair. Need to check more to find problem.

**Comment by docularxu** [comment] 2015-05-05 13:06
Tested snapshot builds 254, the bluetooth can power up in less than 2 seconds.

**Comment by docularxu** [comment] 2015-05-05 13:39
Bisecting shows this regression is introduced by:
  d17a7fb Merge pull request #57 from Leo-Yan/fix_console_spurious_char_0428

Easy solution will be revert this. 

But, as most patches in this merge request are backported from mainline kernel, I am a little worried the latest mainline kernel (4.0 +) may have the same issue for TI's bluetooth.

**Comment by docularxu** [comment] 2015-05-06 07:22
https://github.com/96boards/linux/pull/65
From Leo-Yan: ARM also has committed patches to fix these two issues, so just revert my own patches and directly apply ARM patches.

Verified on snapshot 289. Fixed.

**Closed by docularxu** 2015-05-06 07:22 UTC
Labels: Debian Image, kernel
